---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: java21
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: java21
rules:
  - apiGroups: ["", "apps"]
    resources: ["pods", "deployments", "services"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: java21
  namespace: default
subjects:
  - kind: ServiceAccount
    name: java21
    apiGroup: ""
roleRef:
  kind: Role
  name: java21
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: java21
spec:
  terminationGracePeriodSeconds: 0
  serviceAccountName: java21
  containers:
  - name: java21
    image: eclipse-temurin:21-jre
    command: ["sleep", "inf"]
