---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: java8
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: java8
rules:
  - apiGroups: ["", "apps"]
    resources: ["pods", "deployments", "services"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: java8
  namespace: default
subjects:
  - kind: ServiceAccount
    name: java8
    apiGroup: ""
roleRef:
  kind: Role
  name: java8
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: java8
spec:
  terminationGracePeriodSeconds: 0
  serviceAccountName: java8
  containers:
  - name: java8
    image: eclipse-temurin:8-jre
    command: ["sleep", "inf"]
