ledger:
  ledgerProperties: |
    scalar.db.storage=jdbc
    scalar.db.contact_points=jdbc:postgresql://dummy.default.svc.cluster.local:5432/postgres
    scalar.db.username=postgres
    scalar.db.password=postgres

envoy:
  enabled: false
