ledger:
  ledgerProperties: |
    scalar.db.storage=jdbc
    scalar.db.contact_points=jdbc:sqlite:/tmp/sqlite.db?busy_timeout=10000
  imagePullSecrets:
    - name: reg-docker-secrets

envoy:
  enabled: false
