scalardbCluster:
  image:
    repository: "ghcr.io/scalar-labs/scalardb-cluster-node"
  scalardbClusterNodeProperties: |
    scalar.db.cluster.membership.type=KUBERNETES
    scalar.db.cluster.membership.kubernetes.endpoint.namespace_name=${env:SCALAR_DB_CLUSTER_MEMBERSHIP_KUBERNETES_ENDPOINT_NAMESPACE_NAME}
    scalar.db.cluster.membership.kubernetes.endpoint.name=${env:SCALAR_DB_CLUSTER_MEMBERSHIP_KUBERNETES_ENDPOINT_NAME}
    scalar.db.storage=jdbc
    scalar.db.contact_points=jdbc:sqlite:/sqlite/tmp.db?busy_timeout=10000
  imagePullSecrets:
    - name: reg-docker-secrets
  extraVolumes:
    - name: sqlite
      persistentVolumeClaim:
        claimName: sqlite
  extraVolumeMounts:
    - name: sqlite
      mountPath: /sqlite

envoy:
  enabled: false
