auditor:
  image:
    repository: "ghcr.io/scalar-labs/scalardl-auditor"
  auditorProperties: |
    scalar.db.storage=jdbc
    scalar.db.contact_points=jdbc:sqlite:/tmp/sqlite.db?busy_timeout=10000
    scalar.dl.auditor.cert_holder_id=auditor
    scalar.dl.auditor.cert_path=/keys/certificate
    scalar.dl.auditor.private_key_path=/keys/private-key
  imagePullSecrets:
    - name: reg-docker-secrets

envoy:
  enabled: false
