name: Run the end-to-end test

on:
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest

    env:
      HELM_VERSION: v3.12.2
      DOCKER_REGISTRY_PASSWORD: ${{ secrets.CR_PAT }}
      DOCKER_REGISTRY_USERNAME: scalar-git
      DOCKER_REGISTRY_SERVER: ghcr.io

    strategy:
      matrix:
        productName:
          - scalardb
          - scalardb-cluster
          - scalardl
          - scalardl-audit

    steps:
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - uses: actions/checkout@v3

      - uses: helm/kind-action@v1.7.0
        with:
          cluster_name: kind

      - name: Set up helm command
        uses: azure/setup-helm@v3
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Add Helm repository
        run: |
          helm repo add scalar https://scalar-labs.github.io/helm-charts

      - name: Create secret resource for ScalarDL Auditor
        if: ${{ matrix.productName == 'scalardl-audit' }}
        run: |
          kubectl create secret generic auditor-keys --from-file=certificate=.github/keys-and-certs/auditor-cert.pem --from-file=private-key=.github/keys-and-certs/auditor-key.pem

      - name: Deploy Scalar products to Kind
        run: |
          helm install foo scalar-labs/${{ matrix.productName }} -f .github/manifests/${{ matrix.productName }}.yaml

      - name: Wait for ScalarDB Cluster is started
        if: ${{ matrix.productName == 'scalardb-cluster' }}
        run: |
          kubectl wait --for=condition=Available deployment/foo-${{ matrix.productName }}-node

      - name: Wait for Scalar products are started
        if: ${{ matrix.productName != 'scalardb-cluster' }}
        run: |
          kubectl wait --for=condition=Available deployment/foo-${{ matrix.productName }}

      - name: Build Shadow Jar
        run: ./gradlew shadowJar

      - name: Copy Shadow Jar to tester Pod
        run: |
          kubectl wait --for=condition=Ready pod/java8
          kubectl cp cli/build/libs/scalar-admin-k8s-cli-1.0.0-SNAPSHOT.jar java8:/tmp

      - name: Run Shadow Jar
        run: |
          kubectl exec -it java8 -- java -jar /tmp/scalar-admin-k8s-cli-1.0.0-SNAPSHOT.jar -r foo
