name: Publish the Java Package to Maven Central Repository and upload tool to GitHub

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Set version by tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          VERSION=$(echo ${{ github.ref }} | sed -e "s#refs/tags/v##g")
          echo "version=${VERSION}" >> $GITHUB_ENV

      - name: Set version by the latest project version (for SNAPSHOT)
        if: github.ref == 'refs/heads/main'
        run: |
          VERSION=$(./gradlew :lib:properties -q | grep "version:" | awk '{print $2}')
          echo "version=${VERSION}" >> $GITHUB_ENV

      - name: Upload the package to Maven Central Repository
        run: |
          echo "${{ secrets.SIGNING_SECRET_KEY_RING }}" | base64 -d > ~/.gradle/secring.gpg
          ./gradlew publish \
          -Pversion=${{ env.version }} \
          -Psigning.keyId="${{ secrets.SIGNING_KEY_ID }}" \
          -P'signing.password'="${{ secrets.SIGNING_PASSWORD }}" \
          -Psigning.secretKeyRingFile="$(echo ~/.gradle/secring.gpg)" \
          -PossrhUsername="${{ secrets.OSSRH_USERNAMAE }}" \
          -PossrhPassword="${{ secrets.OSSRH_PASSWORD }}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build Docker image
        run: ./gradlew docker

      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/scalar-labs/scalar-admin-k8s:${{ env.version }}
